### ISSUE TITLE
Login buttons mouseover color

### ISSUE THREAD

**Issue by Zer0-One** [qTox/qTox#2368]
When the mouse cursor is over the "Load" or "Create Profile" button on the login window, the button's color should change in order to indicate that the control is active (like EVERY other button everywhere).

**Comment by antis81** [comment]
Related to #2333. @zetok Could you fix it there? Can be set in the css pseudo-state `hover` …

**Comment by zetok** [comment]
@antis81 I'll see what I can do

**Comment by antis81** [comment]
@zetok Just add something like this:

``` css
QAbstractButton {
border-radius:5px;
padding:5px;
color:white;
background-color:#6cc865;
}

QAbstractButton:hover {
background: #0c530d;
}
```

**EDIT:** You can replace the css code directly (just change the colors).

**Comment by zetok** [comment]
Sorry, I can't get it working. Someone else should do it.

**Comment by SkyzohKey** [comment]
``` css
QAbstractButton:hover,
QAbstractButton:active,
QAbstractButton:focus {
    background-color: #0c530d;
}
```

should do the work. :)
